#!/usr/bin/env bash
# =============================================================================
# harness-ai CLI
#
# Single implementation for both entry points:
#   - devcontainer: the `harnessai` launcher (generated by install.sh) fetches
#     this exact file at the pinned feature version and runs it with --ref.
#   - standalone:   curl -fsSL https://raw.githubusercontent.com/.../cli.sh | bash
#
# Nothing about harness-ai is vendored anywhere: every run clones the
# harness-ai repo (harness.py + content/) at --ref (default: main), so
# there is no packaging step that can silently drop an asset.
#
# Subcommands:
#   install         Resolve config, install enabled binaries, run the scaffold.
#                   Default when no subcommand is given (curl | bash unchanged).
#   sync            Fast path: skip binary installs, hash-check before re-scaffolding.
#   init-extension  Scaffold a minimal starter content-repo extension at <path>.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/harness-ai/main/cli.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/harness-ai/main/cli.sh -o harness-ai.sh
#   bash harness-ai.sh [install|sync] [OPTIONS]
#   bash harness-ai.sh init-extension <path> [--name <str>]
#
# Options:
#   --workspace DIR              Target workspace directory (default: current dir)
#   --tools claude|opencode|...  Comma-separated tools (default: claude; overridden by .harness-ai/config.yaml)
#   --no-mcp                     Skip .mcp.json creation
#   --no-hooks                   Skip hooks file management
#   --no-settings                Skip settings file creation
#   --no-gitignore                Skip .gitignore update
#   --no-defaults                Skip bundled default content (use only --content-repo)
#   --content-repo URL[,URL...]  Comma-separated content-repo URLs, merged in order (later wins on key collision)
#   --content-repo-ref REF[,REF...]   Matching comma-list of refs (default: main for any not given)
#   --content-repo-name NAME[,NAME...] Matching comma-list of names (default: derived from each URL)
#   --content-repo-local-path [NAME=]DIR  Repeatable: use a local content-repo checkout instead of cloning (dev/test).
#                                          NAME must match a configured contentRepos entry to override it.
#                                          Bare DIR (no NAME=) only applies when zero repos are configured at all
#                                          (the init-extension/local-testing workflow — see AGENTS.md).
#   --skills-include-categories LIST  Comma-separated category/category.subcategory allowlist
#   --skills-include-keys LIST        Comma-separated explicit skill-key allowlist
#   --skills-exclude-keys LIST        Comma-separated explicit skill-key denylist
#   --ref BRANCH|TAG             harness-ai git ref to clone (default: main)
#   --local-path DIR             Use a local harness-ai checkout instead of cloning (dev/test, implies --force)
#   --no-rtk                     Skip RTK install and its Claude/OpenCode hooks
#   --no-headroom                Skip the Headroom CLI install
#   --wikictl                    Install wikictl (CLI + MCP server + skills; off by default)
#   --force                      Ignore the .harness-ai/lock hash and re-scaffold
#   --interactive                Guided prompt mode
#   --name <str>                 Extension display name (init-extension only)
#   -h, --help                   Show this help
#
# All of the above are just defaults: `.harness-ai/config.yaml` in the
# target workspace, when present, wins over any flag for the same setting.
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults (.harness-ai/config.yaml overrides these)
# ---------------------------------------------------------------------------
SUBCOMMAND="install"
WORKSPACE="${PWD}"
TOOLS="claude"
CREATE_FILE_MCP="true"
CREATE_FILE_HOOKS="true"
CREATE_FILE_SETTING="true"
UPDATE_GITIGNORE="true"
INSTALL_DEFAULTS="true"
CONTENT_REPO=""
CONTENT_REPO_REF="main"
CONTENT_REPO_NAME=""
declare -a CONTENT_REPO_LOCAL_PATH_RAW=()
GIT_REF="main"
LOCAL_PATH=""
INSTALL_RTK="true"
INSTALL_HEADROOM="true"
INSTALL_WIKICTL="false"
INSTALL_OPENSPEC="true"
CUSTOM_TOOLS=""
CAVEMAN="true"
SKILLS_INCLUDE_CATEGORIES=""
SKILLS_INCLUDE_KEYS=""
SKILLS_EXCLUDE_CATEGORIES=""
SKILLS_EXCLUDE_KEYS=""
FORCE="false"
INTERACTIVE="false"
EXTENSION_PATH=""
EXTENSION_NAME=""
readonly REPO_URL="https://github.com/FabrizioCafolla/harness-ai.git"
SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_NAME

TEMP_DIR=""
PYTHON="python3"
HARNESS_SRC=""

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
cleanup() {
    if [[ -n "${TEMP_DIR:-}" && -d "$TEMP_DIR" ]]; then
        rm -rf "$TEMP_DIR"
    fi
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
die()  { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "  $*"; }
warn() { echo "[WARN]  $*" >&2; }

usage() {
    cat <<EOF
harness-ai  scaffold AI agent/skill assets into any workspace

Usage: $SCRIPT_NAME [install|sync] [OPTIONS]
       $SCRIPT_NAME init-extension <path> [--name <str>]
       curl -fsSL https://raw.githubusercontent.com/FabrizioCafolla/harness-ai/main/cli.sh | bash -s -- [install|sync] [OPTIONS]

Subcommands:
  install                 Install enabled binaries + run the scaffold (default)
  sync                    Fast path: skip binary installs, hash-check before re-scaffolding
  init-extension <path>   Scaffold a minimal starter content-repo extension at <path>

Options:
  --workspace DIR         Target workspace directory (default: current dir)
  --tools LIST            Comma-separated tools: claude, opencode (default: claude)
  --no-mcp                Skip .mcp.json creation
  --no-hooks              Skip hooks file management
  --no-settings           Skip settings file creation
  --no-gitignore          Skip .gitignore update
  --no-defaults           Skip bundled default content
  --content-repo URL[,URL...]       Comma-separated content-repo URLs, merged in order
  --content-repo-ref REF[,REF...]   Matching comma-list of refs (default: main)
  --content-repo-name NAME[,NAME...] Matching comma-list of names (default: derived from URL)
  --content-repo-local-path [NAME=]DIR  Repeatable: local content-repo checkout instead of cloning (dev/test)
  --skills-include-categories LIST  Comma-separated category/category.subcategory allowlist
  --skills-include-keys LIST        Comma-separated explicit skill-key allowlist
  --skills-exclude-keys LIST        Comma-separated explicit skill-key denylist
  --ref BRANCH|TAG        harness-ai git ref to clone (default: main)
  --local-path DIR        Use a local harness-ai checkout instead of cloning (dev/test, implies --force)
  --no-rtk                Skip RTK install and its Claude/OpenCode hooks
  --no-headroom           Skip the Headroom CLI install
  --wikictl               Install wikictl (file-based AI memory: CLI + MCP server + skills; off by default)
  --no-openspec           Skip the openspec CLI install (npm; installed by default)
  --no-caveman            Don't default AGENTS.md to caveman-mode instructions (on by default)
  --force                 Ignore the .harness-ai/lock hash and re-scaffold
  --interactive           Guided prompt mode
  --name <str>            Extension display name (init-extension only)
  -h, --help              Show this help

.harness-ai/config.yaml in the target workspace, when present, overrides
any of the above for the same setting.
EOF
    exit 0
}

# ---------------------------------------------------------------------------
# Interactive mode pure bash prompts
# ---------------------------------------------------------------------------
_prompt() {
    local question="$1" default="$2" varname="$3"
    local answer
    printf "  %s [%s]: " "${question}" "${default}"
    read -r answer
    answer="${answer:-${default}}"
    printf -v "${varname}" '%s' "${answer}"
}

_prompt_bool() {
    local question="$1" default="$2" varname="$3"
    local display answer
    display=$([ "${default}" = "true" ] && echo "Y/n" || echo "y/N")
    printf "  %s? [%s]: " "${question}" "${display}"
    read -r answer
    case "${answer,,}" in
        y|yes) printf -v "${varname}" '%s' "true" ;;
        n|no)  printf -v "${varname}" '%s' "false" ;;
        *)     printf -v "${varname}" '%s' "${default}" ;;
    esac
}

run_interactive() {
    echo ""
    echo "  harness-ai interactive setup"
    echo "  ─────────────────────────────────────────"
    _prompt       "tools (comma-separated: claude, opencode)" "${TOOLS}"         TOOLS
    _prompt_bool  "createFileMCP"                             "${CREATE_FILE_MCP}"      CREATE_FILE_MCP
    _prompt_bool  "createFileHooks"                           "${CREATE_FILE_HOOKS}"    CREATE_FILE_HOOKS
    _prompt_bool  "createFileSetting"                         "${CREATE_FILE_SETTING}"  CREATE_FILE_SETTING
    _prompt_bool  "updateGitignore"                           "${UPDATE_GITIGNORE}"     UPDATE_GITIGNORE
    _prompt_bool  "installDefaults"                           "${INSTALL_DEFAULTS}"     INSTALL_DEFAULTS
    _prompt_bool  "installRtk"                                "${INSTALL_RTK}"          INSTALL_RTK
    _prompt_bool  "installHeadroom"                           "${INSTALL_HEADROOM}"     INSTALL_HEADROOM
    _prompt_bool  "installWikictl"                            "${INSTALL_WIKICTL}"      INSTALL_WIKICTL
    _prompt_bool  "installOpenspec"                           "${INSTALL_OPENSPEC}"     INSTALL_OPENSPEC
    _prompt_bool  "caveman"                                   "${CAVEMAN}"              CAVEMAN
    _prompt       "contentRepos (comma-separated GitHub URLs, leave blank to skip)" "" CONTENT_REPO
    if [[ -n "${CONTENT_REPO}" ]]; then
        _prompt   "contentRepoRef(s) (comma-separated, matching contentRepos order)" "${CONTENT_REPO_REF}" CONTENT_REPO_REF
        _prompt   "contentRepoName(s) (comma-separated, matching contentRepos order; blank = derive from URL)" "" CONTENT_REPO_NAME
    fi
    _prompt       "skills.include.categories (comma-separated, blank = install everything)" "" SKILLS_INCLUDE_CATEGORIES
    echo ""
}

# ---------------------------------------------------------------------------
# Content repo helpers
# ---------------------------------------------------------------------------
_get_remote_sha() {
    local url="$1" ref="$2"
    local auth_url="${url}"

    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        auth_url="https://x-access-token:${GITHUB_TOKEN}@${url#https://}"
    elif command -v gh &>/dev/null && gh auth token &>/dev/null 2>&1; then
        local token
        token=$(gh auth token)
        auth_url="https://x-access-token:${token}@${url#https://}"
    fi

    git ls-remote --exit-code "${auth_url}" "refs/heads/${ref}" 2>/dev/null | cut -f1 || echo ""
}

_clone_content_repo() {
    local url="$1" ref="$2" dest="$3"
    local auth_url="${url}"

    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        auth_url="https://x-access-token:${GITHUB_TOKEN}@${url#https://}"
    elif command -v gh &>/dev/null && gh auth token &>/dev/null 2>&1; then
        local token
        token=$(gh auth token)
        auth_url="https://x-access-token:${token}@${url#https://}"
    fi

    if ! git clone --quiet --depth 1 \
        --branch "${ref}" "${auth_url}" "${dest}" 2>/dev/null; then
        die "Failed to clone content repo: ${url} (ref: ${ref}). For private repos, set GITHUB_TOKEN."
    fi
    info "Content repo cloned (ref: ${ref})"
}

# ---------------------------------------------------------------------------
# Multi-repo helpers — build/decode the CFG_CONTENT_REPOS delimited blob
# (same \x1e/\x1f pattern as CFG_CUSTOM_TOOLS, see _read_config), and resolve
# each named repo to a local path (clone, or a --content-repo-local-path
# dev/test override) before invoking harness.py. See design.md D2/D3.
# ---------------------------------------------------------------------------
_slugify_url() {
    local url="$1" slug
    slug="${url%.git}"
    slug="${slug##*/}"
    slug="${slug,,}"
    [[ -z "${slug}" ]] && slug="content-repo"
    echo "${slug}"
}

# Builds the CFG_CONTENT_REPOS-shaped blob from CLI-flag comma-lists
# (CONTENT_REPO / CONTENT_REPO_REF / CONTENT_REPO_NAME) — used only as the
# fallback default when .harness-ai/config.yaml doesn't set contentRepos.
_build_content_repos_blob_from_flags() {
    [[ -z "${CONTENT_REPO}" ]] && return 0
    local -a urls names refs
    IFS=',' read -ra urls <<<"${CONTENT_REPO}"
    IFS=',' read -ra names <<<"${CONTENT_REPO_NAME}"
    IFS=',' read -ra refs <<<"${CONTENT_REPO_REF}"
    local blob="" i url name ref
    for i in "${!urls[@]}"; do
        url="${urls[$i]}"
        name="${names[$i]:-}"
        [[ -z "${name}" ]] && name="$(_slugify_url "${url}")"
        ref="${refs[$i]:-main}"
        [[ -z "${ref}" ]] && ref="main"
        [[ -n "${blob}" ]] && blob+=$'\x1e'
        blob+="${name}"$'\x1f'"${url}"$'\x1f'"${ref}"
    done
    printf '%s' "${blob}"
}

# Decodes CONTENT_REPOS_BLOB into parallel arrays, name-ordered as configured.
_decode_content_repos() {
    CONTENT_REPO_NAMES=()
    CONTENT_REPO_URLS=()
    CONTENT_REPO_REFS=()
    [[ -z "${CONTENT_REPOS_BLOB:-}" || "${CONTENT_REPOS_BLOB}" == "__none__" ]] && return 0
    local entries=()
    mapfile -d $'\x1e' -t entries <<<"${CONTENT_REPOS_BLOB}"
    local entry name rest url ref
    for entry in "${entries[@]}"; do
        entry="${entry%$'\n'}"
        [[ -z "${entry}" ]] && continue
        name="${entry%%$'\x1f'*}"
        rest="${entry#*$'\x1f'}"
        url="${rest%%$'\x1f'*}"
        ref="${rest#*$'\x1f'}"
        CONTENT_REPO_NAMES+=("${name}")
        CONTENT_REPO_URLS+=("${url}")
        CONTENT_REPO_REFS+=("${ref:-main}")
    done
}

# Builds the name->local-path override map from repeated
# --content-repo-local-path [NAME=]DIR flags. A bare DIR (no NAME=) is kept
# under the __unnamed__ key — the legacy single-repo dev workflow
# (`cli.sh install --content-repo-local-path ./my-extension`, no configured
# contentRepos at all; see AGENTS.md's "Extending harness-ai").
_build_content_repo_overrides() {
    declare -gA CONTENT_REPO_LOCAL_PATH_OVERRIDES=()
    local raw
    for raw in "${CONTENT_REPO_LOCAL_PATH_RAW[@]:-}"; do
        [[ -z "${raw}" ]] && continue
        if [[ "${raw}" == *=* ]]; then
            CONTENT_REPO_LOCAL_PATH_OVERRIDES["${raw%%=*}"]="${raw#*=}"
        else
            CONTENT_REPO_LOCAL_PATH_OVERRIDES["__unnamed__"]="${raw}"
        fi
    done
}

# Resolves every configured repo to a local path: an override wins, otherwise
# a fresh shallow clone into ${TEMP_DIR}/content-repo/<name>/. Populates
# CONTENT_REPO_RESOLVED_PATHS (parallel to CONTENT_REPO_NAMES).
_resolve_content_repos() {
    CONTENT_REPO_RESOLVED_PATHS=()

    if [[ ${#CONTENT_REPO_NAMES[@]} -eq 0 && -n "${CONTENT_REPO_LOCAL_PATH_OVERRIDES[__unnamed__]:-}" ]]; then
        CONTENT_REPO_NAMES=("$(_slugify_url "${CONTENT_REPO_LOCAL_PATH_OVERRIDES[__unnamed__]}")")
        CONTENT_REPO_RESOLVED_PATHS=("${CONTENT_REPO_LOCAL_PATH_OVERRIDES[__unnamed__]}")
        return 0
    fi

    local i name url ref override dest
    for i in "${!CONTENT_REPO_NAMES[@]}"; do
        name="${CONTENT_REPO_NAMES[$i]}"
        url="${CONTENT_REPO_URLS[$i]}"
        ref="${CONTENT_REPO_REFS[$i]}"
        override="${CONTENT_REPO_LOCAL_PATH_OVERRIDES[${name}]:-}"
        if [[ -n "${override}" ]]; then
            CONTENT_REPO_RESOLVED_PATHS+=("${override}")
            continue
        fi
        dest="${TEMP_DIR}/content-repo/${name}"
        info "Cloning content repo '${name}' (ref: ${ref})..."
        _clone_content_repo "${url}" "${ref}" "${dest}"
        CONTENT_REPO_RESOLVED_PATHS+=("${dest}")
    done
}

# Resolves every configured repo's remote HEAD SHA via ls-remote (no clone).
# Returns non-zero (and stops early) if any repo's SHA can't be resolved —
# an incomplete hash would let cmd_sync's fast path falsely report "no
# changes" for private content it couldn't authenticate against.
_resolve_content_repo_shas() {
    CONTENT_REPO_SHAS=()
    local i name url ref sha
    for i in "${!CONTENT_REPO_NAMES[@]}"; do
        name="${CONTENT_REPO_NAMES[$i]}"
        url="${CONTENT_REPO_URLS[$i]}"
        ref="${CONTENT_REPO_REFS[$i]}"
        sha=$(_get_remote_sha "${url}" "${ref}")
        [[ -z "${sha}" ]] && return 1
        CONTENT_REPO_SHAS+=("${name}=${sha}")
    done
    return 0
}

# Builds `--content-repos name=path` args for every resolved repo, for
# harness.py's argparse (task 2.4/3.11).
_content_repos_args() {
    local i
    for i in "${!CONTENT_REPO_NAMES[@]}"; do
        printf '%s\n' "--content-repos" "${CONTENT_REPO_NAMES[$i]}=${CONTENT_REPO_RESOLVED_PATHS[$i]}"
    done
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
if [[ $# -gt 0 && "$1" != -* ]]; then
    case "$1" in
        install|sync) SUBCOMMAND="$1"; shift ;;
        init-extension)
            SUBCOMMAND="$1"; shift
            [[ $# -gt 0 && "$1" != -* ]] || die "init-extension requires a <path> argument. Use -h for help."
            EXTENSION_PATH="$1"; shift
            ;;
        *) die "Unknown subcommand: $1. Expected 'install', 'sync', or 'init-extension'. Use -h for help." ;;
    esac
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --workspace)          WORKSPACE="$2";             shift 2 ;;
        --tools)              TOOLS="$2";                 shift 2 ;;
        --no-mcp)             CREATE_FILE_MCP="false";    shift ;;
        --no-hooks)           CREATE_FILE_HOOKS="false";  shift ;;
        --no-settings)        CREATE_FILE_SETTING="false"; shift ;;
        --no-gitignore)       UPDATE_GITIGNORE="false";   shift ;;
        --no-defaults)        INSTALL_DEFAULTS="false";   shift ;;
        --content-repo)       CONTENT_REPO="$2";          shift 2 ;;
        --content-repo-ref)   CONTENT_REPO_REF="$2";      shift 2 ;;
        --content-repo-name)  CONTENT_REPO_NAME="$2";     shift 2 ;;
        --content-repo-local-path) CONTENT_REPO_LOCAL_PATH_RAW+=("$2"); shift 2 ;;
        --skills-include-categories) SKILLS_INCLUDE_CATEGORIES="$2"; shift 2 ;;
        --skills-include-keys)       SKILLS_INCLUDE_KEYS="$2";       shift 2 ;;
        --skills-exclude-keys)       SKILLS_EXCLUDE_KEYS="$2";       shift 2 ;;
        --ref)                GIT_REF="$2";               shift 2 ;;
        --local-path)         LOCAL_PATH="$2";            shift 2 ;;
        --no-rtk)             INSTALL_RTK="false";        shift ;;
        --no-headroom)        INSTALL_HEADROOM="false";   shift ;;
        --wikictl)            INSTALL_WIKICTL="true";     shift ;;
        --no-openspec)        INSTALL_OPENSPEC="false";   shift ;;
        --no-caveman)         CAVEMAN="false";            shift ;;
        --force)              FORCE="true";               shift ;;
        --interactive)        INTERACTIVE="true";          shift ;;
        --name)                EXTENSION_NAME="$2";        shift 2 ;;
        -h|--help)            usage ;;
        *) die "Unknown option: $1. Use -h for help." ;;
    esac
done

# ---------------------------------------------------------------------------
# Interactive mode (runs after flag parsing so flags set the defaults)
# ---------------------------------------------------------------------------
if [[ "${INTERACTIVE}" == "true" ]]; then
    run_interactive
fi

# ---------------------------------------------------------------------------
# init-extension: scaffold a minimal starter content-repo extension.
#
# Generates the lean shape the one real extension in production use actually
# has (agents/ + skills/, each with metadata.yml + one placeholder body, plus
# a top-level agents.harness-ai.md and README) — not the fully-documented
# format (hooks/, mcp.json, paths.yml are optional/advanced and are noted,
# not scaffolded; see design.md D5). Pure bash, no git/python dependency, so
# it dispatches before the dependency checks below.
# ---------------------------------------------------------------------------
cmd_init_extension() {
    local name="${EXTENSION_NAME:-$(basename "${EXTENSION_PATH}")}"

    if [[ -e "${EXTENSION_PATH}" && -n "$(ls -A "${EXTENSION_PATH}" 2>/dev/null)" ]]; then
        die "'${EXTENSION_PATH}' already exists and is not empty."
    fi

    mkdir -p "${EXTENSION_PATH}/agents" "${EXTENSION_PATH}/skills/example-skill"

    cat >"${EXTENSION_PATH}/agents/metadata.yml" <<'EOF'
default:
  claude:
  opencode:

agents:
  example-agent:
    claude:
      name: Example Agent
      description: >-
        Replace with a description of when this agent should be selected
        (Claude Code's Agent tool subagent_type / FleetView agent picker).
      allowedTools:
        - Read
        - Edit
    opencode:
      name: Example Agent
      description: >-
        Replace with a description of when this agent should be selected.
      mode: subagent
EOF

    cat >"${EXTENSION_PATH}/agents/example-agent.md" <<'EOF'
You are Example Agent. Replace this body with the agent's system prompt —
its role, workflow, and constraints. No frontmatter here: name/description/
tools come from metadata.yml and are injected at scaffold time.
EOF

    cat >"${EXTENSION_PATH}/skills/metadata.yml" <<'EOF'
default:
  claude:
    license: MIT
  opencode:
    license: MIT

skills:
  example-skill:
    # See AGENTS.md's Taxonomy table for the full category/subcategory list.
    category: engineering
    subcategory: build-and-quality
    claude:
      name: example-skill
      description: >-
        Replace with a specific "Use when..." trigger description — this is
        what the model reads to decide when to invoke the skill.
    opencode:
      name: example-skill
      description: >-
        Replace with a specific "Use when..." trigger description.
EOF

    cat >"${EXTENSION_PATH}/skills/example-skill/SKILL.md" <<'EOF'
Replace this body with the skill's instructions. No frontmatter here:
name/description come from metadata.yml and are injected at scaffold time.
EOF

    cat >"${EXTENSION_PATH}/agents.harness-ai.md" <<'EOF'
<!-- Optional static content appended to every scaffolded workspace's
     AGENTS.md managed block. Leave empty to skip, or add project-wide
     instructions specific to this extension. -->
EOF

    cat >"${EXTENSION_PATH}/README.md" <<EOF
# ${name}

Content-repo extension for [harness-ai](https://github.com/FabrizioCafolla/harness-ai).

## Usage

\`\`\`bash
bash cli.sh install --content-repo https://github.com/your-org/${name}
\`\`\`

Or, while iterating locally:

\`\`\`bash
bash cli.sh install --content-repo-local-path /path/to/${name}
\`\`\`

## What's in here

- \`agents/metadata.yml\` + \`agents/<key>.md\` — one placeholder agent
- \`skills/metadata.yml\` + \`skills/<key>/SKILL.md\` — one placeholder skill
- \`agents.harness-ai.md\` — static content appended to every scaffolded AGENTS.md

This is the lean shape real harness-ai extensions use. \`hooks/\`, \`mcp.json\`,
and \`paths.yml\` overrides are also supported but optional/advanced — see
harness-ai's AGENTS.md ("Content Repo Format" / "Content repo overrides")
before adding them.

## Taxonomy

Every skill entry in \`skills/metadata.yml\` needs \`category\`/\`subcategory\`.
See harness-ai's AGENTS.md Taxonomy table for the valid values, and its
Public skill inventory for examples.

## Inventory

| Kind  | Key             | Category    | Subcategory        |
| ----- | --------------- | ----------- | ------------------- |
| Agent | \`example-agent\` | —           | —                    |
| Skill | \`example-skill\` | engineering | build-and-quality    |
EOF

    info "Generated harness-ai extension at ${EXTENSION_PATH}"
    info "Next: replace the placeholder agent/skill, then:"
    info "  bash cli.sh install --content-repo-local-path ${EXTENSION_PATH}"
}

if [[ "${SUBCOMMAND}" == "init-extension" ]]; then
    cmd_init_extension
    exit 0
fi

# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------
for cmd in git python3; do
    command -v "$cmd" &>/dev/null || die "'$cmd' is required but not found."
done

PY_MAJOR=$(python3 -c 'import sys; print(sys.version_info.major)')
PY_MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 9 ]]; then
    PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    die "Python 3.9+ required, found ${PY_VERSION}."
fi

# ---------------------------------------------------------------------------
# Setup: temp dir, pyyaml venv
# ---------------------------------------------------------------------------
TEMP_DIR="$(mktemp -d)"

_setup_python() {
    if ! python3 -c 'import yaml' 2>/dev/null; then
        info "Installing pyyaml in isolated venv..."
        python3 -m venv "${TEMP_DIR}/venv"
        "${TEMP_DIR}/venv/bin/pip" install --quiet pyyaml \
            || die "Failed to install pyyaml inside venv."
        PYTHON="${TEMP_DIR}/venv/bin/python3"
    fi
}

# ---------------------------------------------------------------------------
# Resolve harness-ai source: local checkout (dev/test) or fresh clone at --ref
# ---------------------------------------------------------------------------
_resolve_harness_ai_source() {
    HARNESS_SRC="${TEMP_DIR}/harness-ai"
    if [[ -n "${LOCAL_PATH}" ]]; then
        [[ -f "${LOCAL_PATH}/harness.py" ]] \
            || die "--local-path '${LOCAL_PATH}' is not a harness-ai checkout (harness.py not found)."
        info "Using local harness-ai checkout: ${LOCAL_PATH}"
        cp -R "${LOCAL_PATH}" "${HARNESS_SRC}"
    else
        info "Fetching harness-ai (ref: ${GIT_REF})..."
        git clone --quiet --depth 1 --branch "${GIT_REF}" "${REPO_URL}" "${HARNESS_SRC}" \
            || die "Failed to fetch harness-ai at ref '${GIT_REF}' from ${REPO_URL}."
    fi
}

# ---------------------------------------------------------------------------
# .harness-ai/config.yaml: single source of truth, resolved on top of flags
# ---------------------------------------------------------------------------
_read_config() {
    local config_file="$1"
    "${PYTHON}" - "${config_file}" <<'PYEOF'
import re
import shlex
import sys

import yaml

path = sys.argv[1]
with open(path) as f:
    try:
        cfg = yaml.safe_load(f) or {}
    except yaml.YAMLError:
        # No message here on purpose: cli.sh's caller falls back to its own
        # generic "check it is valid YAML" die() message when this script's
        # stderr is empty (see _load_config).
        sys.exit(1)


def emit(name, value):
    if value is None or value == "":
        return
    print(f"{name}={shlex.quote(str(value))}")


tools = cfg.get("tools")
if tools:
    emit("CFG_TOOLS", ",".join(tools))

install = cfg.get("install") or {}
for key, var in (
    ("rtk", "CFG_INSTALL_RTK"),
    ("headroom", "CFG_INSTALL_HEADROOM"),
    ("wikictl", "CFG_INSTALL_WIKICTL"),
    ("openspec", "CFG_INSTALL_OPENSPEC"),
):
    if key in install:
        emit(var, "true" if install[key] else "false")

# Custom tools: variable-length name->command map, which the fixed-arity
# CFG_* scalar bridge above can't carry. Serialized as one delimited blob
# (record separator \x1e between entries, unit separator \x1f between
# name/command) and decoded in _load_config. Kept to exactly these two
# places (here and _load_config's consumer) — see design.md D2.
custom = install.get("custom") or {}
if custom:
    blob = "\x1e".join(f"{name}\x1f{command}" for name, command in custom.items())
    emit("CFG_CUSTOM_TOOLS", blob)

behavior = cfg.get("behavior") or {}
if "caveman" in behavior:
    emit("CFG_CAVEMAN", "true" if behavior["caveman"] else "false")

scaffold = cfg.get("scaffold") or {}
for key, var in (
    ("createFileMCP", "CFG_CREATE_FILE_MCP"),
    ("createFileHooks", "CFG_CREATE_FILE_HOOKS"),
    ("createFileSetting", "CFG_CREATE_FILE_SETTING"),
    ("updateGitignore", "CFG_UPDATE_GITIGNORE"),
    ("installDefaults", "CFG_INSTALL_DEFAULTS"),
):
    if key in scaffold:
        emit(var, "true" if scaffold[key] else "false")

# contentRepos (a list) is the current shape; the old singular contentRepo
# is read as sugar for a one-entry list (name derived from the URL slug),
# with a deprecation warning — see design.md D3. Either way the result is
# emitted as one CFG_CONTENT_REPOS delimited blob (record separator \x1e
# between repos, unit separator \x1f between name/url/ref), decoded in
# _load_config — same pattern as CFG_CUSTOM_TOOLS.
RESERVED_SOURCE_NAMES = {"default", "local"}


def _slugify(url):
    name = url.rstrip("/").rsplit("/", 1)[-1]
    if name.endswith(".git"):
        name = name[: -len(".git")]
    name = re.sub(r"[^a-zA-Z0-9]+", "-", name).strip("-").lower()
    return name or "content-repo"


repos = []
# `"contentRepos" in cfg` (presence), not `cfg.get("contentRepos")` (truthiness):
# an explicit `contentRepos: []` must still override a --content-repo CLI
# flag (config.yaml always wins over flags), not silently fall through to
# it just because an empty list is falsy like an absent key.
content_repos_present = "contentRepos" in cfg
content_repos = cfg.get("contentRepos") or []
if content_repos_present:
    seen_names = set()
    for entry in content_repos:
        entry = entry or {}
        name = entry.get("name")
        if not name:
            sys.exit(f"contentRepos entry missing required 'name' field: {entry}")
        if name in RESERVED_SOURCE_NAMES:
            sys.exit(f"contentRepos name '{name}' is reserved (used internally for the bundled/local sources) — choose a different name")
        if name in seen_names:
            sys.exit(f"contentRepos name '{name}' is used more than once — names must be unique")
        seen_names.add(name)
        if entry.get("url"):
            repos.append((name, entry["url"], entry.get("ref") or "main"))
elif (cfg.get("contentRepo") or {}).get("url"):
    cr = cfg["contentRepo"]
    derived = _slugify(cr["url"])
    if derived in RESERVED_SOURCE_NAMES:
        sys.exit(f"content repo name derived from URL ('{derived}') collides with a reserved source name — set contentRepos explicitly with a different name")
    repos.append((derived, cr["url"], cr.get("ref") or "main"))
    print(
        "[WARN] .harness-ai/config.yaml: 'contentRepo' (singular) is deprecated, use 'contentRepos' (a list) instead",
        file=sys.stderr,
    )

if repos:
    blob = "\x1e".join(f"{name}\x1f{url}\x1f{ref}" for name, url, ref in repos)
    emit("CFG_CONTENT_REPOS", blob)
elif content_repos_present:
    # Explicit empty list: emit a non-empty sentinel so _load_config's
    # `${CFG_CONTENT_REPOS:-<flag fallback>}` doesn't treat "empty" the same
    # as "unset" and fall through to a --content-repo flag anyway.
    print("CFG_CONTENT_REPOS=__none__")

skills = cfg.get("skills") or {}
include = skills.get("include") or {}
exclude = skills.get("exclude") or {}
if include.get("categories"):
    emit("CFG_SKILLS_INCLUDE_CATEGORIES", ",".join(include["categories"]))
if include.get("keys"):
    emit("CFG_SKILLS_INCLUDE_KEYS", ",".join(include["keys"]))
if exclude.get("categories"):
    emit("CFG_SKILLS_EXCLUDE_CATEGORIES", ",".join(exclude["categories"]))
if exclude.get("keys"):
    emit("CFG_SKILLS_EXCLUDE_KEYS", ",".join(exclude["keys"]))
PYEOF
}

_load_config() {
    local config_file="${WORKSPACE}/.harness-ai/config.yaml"
    if [[ -f "${config_file}" ]]; then
        local resolved err_file
        err_file="${TEMP_DIR}/read_config.err"
        # Plain assignment (not `local var=$(...)`) so a parse failure's exit
        # status is actually visible here instead of being masked by `local`.
        # stderr is captured so a specific Python-raised error (e.g. a reserved
        # contentRepos name) can be shown verbatim instead of the generic
        # fallback message; on success, anything captured (e.g. the
        # contentRepo deprecation warning) is replayed to the real stderr.
        if ! resolved="$(_read_config "${config_file}" 2>"${err_file}")"; then
            if [[ -s "${err_file}" ]]; then
                die "$(cat "${err_file}")"
            fi
            die "Failed to parse ${config_file} — check it is valid YAML."
        fi
        [[ -s "${err_file}" ]] && cat "${err_file}" >&2
        eval "${resolved}"
    fi
    TOOLS="${CFG_TOOLS:-${TOOLS}}"
    INSTALL_RTK="${CFG_INSTALL_RTK:-${INSTALL_RTK}}"
    INSTALL_HEADROOM="${CFG_INSTALL_HEADROOM:-${INSTALL_HEADROOM}}"
    INSTALL_WIKICTL="${CFG_INSTALL_WIKICTL:-${INSTALL_WIKICTL}}"
    INSTALL_OPENSPEC="${CFG_INSTALL_OPENSPEC:-${INSTALL_OPENSPEC}}"
    CAVEMAN="${CFG_CAVEMAN:-${CAVEMAN}}"
    CREATE_FILE_MCP="${CFG_CREATE_FILE_MCP:-${CREATE_FILE_MCP}}"
    CREATE_FILE_HOOKS="${CFG_CREATE_FILE_HOOKS:-${CREATE_FILE_HOOKS}}"
    CREATE_FILE_SETTING="${CFG_CREATE_FILE_SETTING:-${CREATE_FILE_SETTING}}"
    UPDATE_GITIGNORE="${CFG_UPDATE_GITIGNORE:-${UPDATE_GITIGNORE}}"
    INSTALL_DEFAULTS="${CFG_INSTALL_DEFAULTS:-${INSTALL_DEFAULTS}}"
    CUSTOM_TOOLS="${CFG_CUSTOM_TOOLS:-${CUSTOM_TOOLS:-}}"
    CONTENT_REPOS_BLOB="${CFG_CONTENT_REPOS:-$(_build_content_repos_blob_from_flags)}"
    SKILLS_INCLUDE_CATEGORIES="${CFG_SKILLS_INCLUDE_CATEGORIES:-${SKILLS_INCLUDE_CATEGORIES}}"
    SKILLS_INCLUDE_KEYS="${CFG_SKILLS_INCLUDE_KEYS:-${SKILLS_INCLUDE_KEYS}}"
    SKILLS_EXCLUDE_CATEGORIES="${CFG_SKILLS_EXCLUDE_CATEGORIES:-${SKILLS_EXCLUDE_CATEGORIES}}"
    SKILLS_EXCLUDE_KEYS="${CFG_SKILLS_EXCLUDE_KEYS:-${SKILLS_EXCLUDE_KEYS}}"
    _decode_content_repos
}

# Copy-once starter config, seeded from the resolved (pre-YAML) fallback
# values — only runs when the workspace has no config.yaml yet.
_seed_starter_config() {
    local config_dir="${WORKSPACE}/.harness-ai"
    local config_file="${config_dir}/config.yaml"
    [[ -f "${config_file}" ]] && return 0

    local template="${HARNESS_SRC}/config/config.default.yaml"
    if [[ ! -f "${template}" ]]; then
        warn "missing config/config.default.yaml template, skipping starter config"
        return 0
    fi

    mkdir -p "${config_dir}"
    # CUSTOM_TOOLS and CONTENT_REPOS_BLOB are both variable-length (a
    # name->command map and a name/url/ref list respectively), so neither
    # fits the fixed positional args below; they travel on fd 3 and fd 4
    # (here-strings), read via os.fdopen() in the script, leaving the other
    # positional args untouched.
    "${PYTHON}" - "${template}" "${config_file}" \
        "${TOOLS}" "${INSTALL_RTK}" "${INSTALL_HEADROOM}" "${INSTALL_WIKICTL}" \
        "${INSTALL_OPENSPEC}" "${CAVEMAN}" \
        "${CREATE_FILE_MCP}" "${CREATE_FILE_HOOKS}" "${CREATE_FILE_SETTING}" \
        "${UPDATE_GITIGNORE}" "${INSTALL_DEFAULTS}" \
        "${SKILLS_INCLUDE_CATEGORIES}" "${SKILLS_INCLUDE_KEYS}" \
        "${SKILLS_EXCLUDE_CATEGORIES}" "${SKILLS_EXCLUDE_KEYS}" \
        3<<<"${CUSTOM_TOOLS}" 4<<<"${CONTENT_REPOS_BLOB}" <<'PYEOF'
import os
import sys

import yaml

(template_path, out_path, tools, i_rtk, i_hr, i_wc, i_os, caveman,
 mcp, hooks, settings, gi, defaults,
 skills_inc_cats, skills_inc_keys, skills_exc_cats, skills_exc_keys) = sys.argv[1:18]

custom_blob = os.fdopen(3).read().rstrip("\n")
content_repos_blob = os.fdopen(4).read().rstrip("\n")


def b(v):
    return v.lower() == "true"


def csv(v):
    return [x for x in v.split(",") if x]


with open(template_path) as f:
    cfg = yaml.safe_load(f)

cfg["tools"] = [t for t in tools.split(",") if t]
cfg["install"]["rtk"] = b(i_rtk)
cfg["install"]["headroom"] = b(i_hr)
cfg["install"]["wikictl"] = b(i_wc)
cfg["install"]["openspec"] = b(i_os)
cfg["install"]["custom"] = (
    dict(entry.split("\x1f", 1) for entry in custom_blob.split("\x1e"))
    if custom_blob
    else {}
)
cfg["behavior"]["caveman"] = b(caveman)
cfg["scaffold"]["createFileMCP"] = b(mcp)
cfg["scaffold"]["createFileHooks"] = b(hooks)
cfg["scaffold"]["createFileSetting"] = b(settings)
cfg["scaffold"]["updateGitignore"] = b(gi)
cfg["scaffold"]["installDefaults"] = b(defaults)

cfg["contentRepos"] = [
    {"name": entry.split("\x1f")[0], "url": entry.split("\x1f")[1], "ref": entry.split("\x1f")[2]}
    for entry in content_repos_blob.split("\x1e")
    if entry
]
cfg["skills"] = {
    "include": {"categories": csv(skills_inc_cats), "keys": csv(skills_inc_keys)},
    "exclude": {"categories": csv(skills_exc_cats), "keys": csv(skills_exc_keys)},
}

with open(out_path, "w") as f:
    yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
PYEOF
    info "Created starter .harness-ai/config.yaml"
}

# ---------------------------------------------------------------------------
# RTK (optional) — install binary and register the Claude PreToolUse hook.
# (OpenCode's RTK activation is a static plugin file, not a merge — see
# harness.py's _apply_opencode_hook; no cli.sh-side step needed for it.)
#
# Binary install (_install_rtk_binary) and hook merge (_merge_rtk_hook) are
# separate on purpose: every run fetches a *fresh* harness-ai clone (nothing
# is vendored), so the hook template in that clone always starts pristine —
# the merge must happen every time a scaffold pass runs, not just when the
# binary needs (re)installing. cmd_sync's full re-scaffold path calls
# _merge_rtk_hook too (via _run_scaffold); it never calls the binary install.
# ---------------------------------------------------------------------------
_install_rtk_binary() {
    if command -v rtk &>/dev/null; then
        info "RTK already installed: $(rtk --version 2>/dev/null || echo 'unknown version')"
        return 0
    fi

    info "Installing RTK..."
    case "$(uname -m)" in
        x86_64 | amd64) RTK_ARCH="x86_64" ;;
        aarch64 | arm64) RTK_ARCH="aarch64" ;;
        *) warn "RTK: unsupported arch $(uname -m), skipping"; return 0 ;;
    esac
    local rtk_bin_dir="/usr/local/bin"
    [[ -w "${rtk_bin_dir}" ]] || rtk_bin_dir="${HOME}/.local/bin"
    mkdir -p "${rtk_bin_dir}"
    if curl -fsSL \
        "https://github.com/rtk-ai/rtk/releases/latest/download/rtk-${RTK_ARCH}-unknown-linux-gnu.tar.gz" \
        | tar xz -C "${rtk_bin_dir}" rtk; then
        chmod 755 "${rtk_bin_dir}/rtk"
        info "RTK installed to ${rtk_bin_dir}/rtk"
    else
        warn "RTK install failed, continuing without it"
    fi
}

_merge_rtk_hook() {
    local hooks_file="${HARNESS_SRC}/config/claude/hooks.json"
    [[ -f "${hooks_file}" ]] || return 0

    RTK_HOOKS_FILE="${hooks_file}" "${PYTHON}" - <<'PYEOF'
import json, os

path = os.environ["RTK_HOOKS_FILE"]
with open(path) as f:
    hooks = json.load(f)

entry = {
    "matcher": "Bash",
    "hooks": [{"type": "command", "command": "rtk hook claude"}],
}
pre = hooks.setdefault("PreToolUse", [])
if not any(
    h.get("command") == "rtk hook claude"
    for item in pre
    for h in item.get("hooks", [])
):
    pre.append(entry)
    with open(path, "w") as f:
        json.dump(hooks, f, indent=2)
        f.write("\n")
    print("  RTK PreToolUse hook added to Claude hooks template")
PYEOF
}

# ---------------------------------------------------------------------------
# uv tool PATH fix — `uv tool install` (Headroom, wikictl) drops binaries into
# uv's own tool-bin dir, which may not be on PATH yet for this same script
# run, so `command -v` right after installing (or a later install step in
# this same run) can miss it. Called once in cmd_install before any installs.
# See design.md D6 — this handles the *same-run* symptom; `uv tool
# update-shell` (called once after the install block) handles the *new-shell*
# symptom.
# ---------------------------------------------------------------------------
_ensure_uv_tool_path() {
    command -v uv &>/dev/null || return 0
    local uv_bin_dir
    uv_bin_dir="$(uv tool dir --bin 2>/dev/null)" || return 0
    [[ -n "${uv_bin_dir}" ]] && export PATH="${uv_bin_dir}:${PATH}"
}

# ---------------------------------------------------------------------------
# Headroom (installed by default) — request-level context compression CLI
#
# Not a hook and not auto-active: activate per-session with `headroom wrap
# <cli>` (e.g. `headroom wrap claude`, `headroom wrap opencode`). RTK stays
# the active input-side layer; Headroom only stacks on top when explicitly
# wrapped.
# ---------------------------------------------------------------------------
_install_headroom() {
    if command -v headroom &>/dev/null; then
        info "Headroom already installed: $(headroom --version 2>/dev/null || echo 'unknown version') (inactive until 'headroom wrap <cli>')"
    elif command -v uv &>/dev/null; then
        info "Installing Headroom CLI..."
        if uv tool install "headroom-ai[proxy]"; then
            info "Headroom installed: $(headroom --version 2>/dev/null || echo 'unknown version') (inactive until 'headroom wrap <cli>')"
        else
            warn "Headroom install failed, continuing without it"
        fi
    else
        warn "Headroom requires uv (not found), skipping"
    fi
}

# ---------------------------------------------------------------------------
# wikictl (optional) — file-based AI memory layer (CLI + MCP server). Installed
# from the fetched harness-ai checkout, mirroring Headroom. The MCP entry and
# skills are wired by harness.py below.
# ---------------------------------------------------------------------------
_install_wikictl() {
    if command -v wikictl &>/dev/null; then
        info "wikictl already installed: $(wikictl --version 2>/dev/null || echo 'unknown version')"
    elif command -v uv &>/dev/null; then
        info "Installing wikictl..."
        if uv tool install "${HARNESS_SRC}/wikictl[serve]"; then
            info "wikictl installed: $(wikictl --version 2>/dev/null || echo 'unknown version')"
        else
            warn "wikictl install failed, continuing without it"
        fi
    else
        warn "wikictl requires uv (not found), skipping"
    fi
}

# ---------------------------------------------------------------------------
# openspec (default on) — the @fission-ai/openspec CLI, installed via npm
# (not uv: it's a Node package, unlike the other three installs above).
# ---------------------------------------------------------------------------
_install_openspec() {
    if command -v openspec &>/dev/null; then
        info "openspec already installed: $(openspec --version 2>/dev/null || echo 'unknown version')"
    elif command -v npm &>/dev/null; then
        info "Installing openspec..."
        if npm install -g @fission-ai/openspec@latest &>/dev/null; then
            info "openspec installed: $(openspec --version 2>/dev/null || echo 'unknown version')"
        else
            warn "openspec install failed, continuing without it"
        fi
    else
        warn "openspec requires npm (not found), skipping"
    fi
}

# ---------------------------------------------------------------------------
# Content-repo custom tools (optional) — a content repo can ship its own
# custom.yaml (same flat name->command shape as install.custom) so its
# commands travel with the repo into every workspace that extends it,
# instead of being copy-pasted into each workspace's config.yaml. Merged
# on top of the workspace's own CUSTOM_TOOLS blob; on a name collision the
# content repo's command wins (it is merged in last).
# ---------------------------------------------------------------------------
_merge_content_custom() {
    local content_repo_dir="$1"
    local custom_file="${content_repo_dir}/custom.yaml"
    [[ -f "${custom_file}" ]] || return 0

    local merged
    merged="$("${PYTHON}" - "${custom_file}" 3<<<"${CUSTOM_TOOLS}" <<'PYEOF'
import os
import sys

import yaml

custom_file = sys.argv[1]
base_blob = os.fdopen(3).read().rstrip("\n")

merged = {}
for entry in base_blob.split("\x1e"):
    if not entry:
        continue
    name, command = entry.split("\x1f", 1)
    merged[name] = command

with open(custom_file) as f:
    overrides = yaml.safe_load(f) or {}
for name, command in overrides.items():
    merged[name] = command

print("\x1e".join(f"{name}\x1f{command}" for name, command in merged.items()))
PYEOF
    )" || die "Failed to parse ${custom_file} — check it is valid YAML."

    CUSTOM_TOOLS="${merged}"
}

# ---------------------------------------------------------------------------
# Custom tools (optional) — arbitrary extra install commands declared under
# install.custom in config.yaml (merged with the content repo's custom.yaml,
# see _merge_content_custom above). No already-installed check (see design.md
# D3): commands are expected to be self-idempotent, same contract mise's
# [tasks] and devbox's init_hook use for the same flat name->command shape.
# ---------------------------------------------------------------------------
_install_custom_tools() {
    # mapfile, not `read -a`: `read` stops at the first newline regardless of
    # IFS, which silently truncated any multi-line custom command at its
    # first embedded `\n`. mapfile -d splits on \x1e across the whole blob.
    local entries=()
    mapfile -d $'\x1e' -t entries <<<"${CUSTOM_TOOLS}"

    local entry name command
    for entry in "${entries[@]}"; do
        [[ -z "${entry}" ]] && continue
        name="${entry%%$'\x1f'*}"
        command="${entry#*$'\x1f'}"
        info "Installing custom tool: ${name}..."
        if bash -c "${command}"; then
            info "Custom tool installed: ${name}"
        else
            warn "Custom tool '${name}' failed to install, continuing"
        fi
    done
}

# ---------------------------------------------------------------------------
# Run harness.py with the fully resolved config
# ---------------------------------------------------------------------------
_run_scaffold() {
    # Re-merge the RTK hook into this run's freshly cloned hooks.json — the
    # clone is always pristine, and harness.py replaces the hooks key wholesale.
    if [[ "${INSTALL_RTK}" == "true" && "${CREATE_FILE_HOOKS}" == "true" ]]; then
        _merge_rtk_hook
    fi

    local extra_args=()
    local line
    while IFS= read -r line; do
        [[ -n "${line}" ]] && extra_args+=("${line}")
    done < <(_content_repos_args)

    "${PYTHON}" "${HARNESS_SRC}/harness.py" \
        --workspace               "${WORKSPACE}" \
        --tools                   "${TOOLS}" \
        --create-file-mcp         "${CREATE_FILE_MCP}" \
        --create-file-hooks       "${CREATE_FILE_HOOKS}" \
        --create-file-setting     "${CREATE_FILE_SETTING}" \
        --update-gitignore        "${UPDATE_GITIGNORE}" \
        --install-defaults        "${INSTALL_DEFAULTS}" \
        --install-wikictl         "${INSTALL_WIKICTL}" \
        --behavior-caveman        "${CAVEMAN}" \
        --skills-include-categories "${SKILLS_INCLUDE_CATEGORIES}" \
        --skills-include-keys       "${SKILLS_INCLUDE_KEYS}" \
        --skills-exclude-categories "${SKILLS_EXCLUDE_CATEGORIES}" \
        --skills-exclude-keys       "${SKILLS_EXCLUDE_KEYS}" \
        "${extra_args[@]+"${extra_args[@]}"}"
}

# ---------------------------------------------------------------------------
# install: resolve config → install enabled binaries → clone content repo → scaffold
# ---------------------------------------------------------------------------
cmd_install() {
    _resolve_harness_ai_source
    _setup_python
    _load_config
    _seed_starter_config
    _build_content_repo_overrides

    _ensure_uv_tool_path
    [[ "${INSTALL_RTK}" == "true" ]] && _install_rtk_binary
    [[ "${INSTALL_HEADROOM}" == "true" ]] && _install_headroom
    [[ "${INSTALL_WIKICTL}" == "true" ]] && _install_wikictl
    [[ "${INSTALL_OPENSPEC}" == "true" ]] && _install_openspec
    # uv's own supported mechanism for making `uv tool install`ed binaries
    # resolvable in *new* shells (this run's PATH export above only covers
    # the current script). Best-effort: never fails the install.
    command -v uv &>/dev/null && { uv tool update-shell 2>/dev/null || true; }

    # Clones each configured repo (or uses a --content-repo-local-path
    # override) into CONTENT_REPO_RESOLVED_PATHS, parallel to CONTENT_REPO_NAMES.
    _resolve_content_repos
    # Custom tools run after every content repo is available so their
    # custom.yaml (if any) is merged into CUSTOM_TOOLS, in config order —
    # later repos' commands win on name collision.
    local repo_path
    for repo_path in "${CONTENT_REPO_RESOLVED_PATHS[@]:-}"; do
        [[ -n "${repo_path}" ]] && _merge_content_custom "${repo_path}"
    done
    [[ -n "${CUSTOM_TOOLS}" ]] && _install_custom_tools

    # The lock hash is identity-based (harness-ai HEAD SHA + content repo SHAs),
    # so uncommitted local changes never alter it: a local checkout always forces.
    if [[ "${FORCE}" == "true" || -n "${LOCAL_PATH}" ]]; then
        if [[ -f "${WORKSPACE}/.harness-ai/lock" ]]; then
            info "Forcing re-scaffold (removing .harness-ai/lock)"
            rm -f "${WORKSPACE}/.harness-ai/lock"
        fi
    fi

    echo ""
    _run_scaffold
}

# ---------------------------------------------------------------------------
# sync: skip binary installs; hash-check via ls-remote before re-scaffolding
# ---------------------------------------------------------------------------
cmd_sync() {
    _resolve_harness_ai_source
    _setup_python
    _load_config
    _build_content_repo_overrides

    # Fast check: skip the full clone+scaffold if every configured repo's SHA
    # resolves. An unresolved SHA (e.g. private repo auth failed) means the
    # hash would be incomplete — a false match could silently skip private
    # content changes — so that falls straight through to a full run instead.
    local shas_ok="false"
    CONTENT_REPO_SHAS=()
    if _resolve_content_repo_shas; then
        shas_ok="true"
    fi

    if [[ ${#CONTENT_REPO_NAMES[@]} -eq 0 || "${shas_ok}" == "true" ]]; then
        local sha_args=() s
        for s in "${CONTENT_REPO_SHAS[@]:-}"; do
            [[ -n "${s}" ]] && sha_args+=(--content-repo-sha "${s}")
        done
        if "${PYTHON}" "${HARNESS_SRC}/harness.py" \
            --workspace "${WORKSPACE}" \
            --check-only \
            "${sha_args[@]+"${sha_args[@]}"}"; then
            exit 0
        fi
    fi

    _resolve_content_repos
    local repo_path
    for repo_path in "${CONTENT_REPO_RESOLVED_PATHS[@]:-}"; do
        [[ -n "${repo_path}" ]] && _merge_content_custom "${repo_path}"
    done
    [[ -n "${CUSTOM_TOOLS}" ]] && _install_custom_tools

    echo ""
    _run_scaffold
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "${SUBCOMMAND}" in
    install) cmd_install ;;
    sync)    cmd_sync ;;
esac
